version: '3.8'
services:
  db:
    image: postgres:latest
    container_name: servidor_postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: how
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - postgres_network

volumes:
  db_data:

networks:
  postgres_network:
    driver: bridge
